### PR TITLE
Remove Num constraint from GoG functions

### PR DESCRIPTION
**Pull request by alex-mckenna**
The functions in the module GoG which create traces have constraints on
Num for input types. As the data is converted to JSON anyway, this is an
unnecessary constraint.

### CODE REVIEW

**Comment by glutamate** [comment]
why?

**Comment by glutamate** [comment]
if you use something like Text in a line  or point plot for x/y axis, then plotly won't know how to plot it. It is true that the Haskell side won't crash, but plotly will throw a runtime error

**Comment by alex-mckenna** [comment]
I want to plot a time series, and it makes more sense to show dates as strings rather than numbers on the chart. Is it possible to recreate something [like this](https://plot.ly/javascript/time-series/) without this patch?

**Comment by glutamate** [comment]
I see. I think the right thing in that case is to pass dates in as Day or UTCTime values, not text. But I think you are right that lifting the num restriction is the right thing to do as we already have the axis value restriction.

**Pull request merged**
