### PR TITLE
Add Mushroom, Titanic datasets

### PR DESCRIPTION
**Pull request by ocramz**
Notes:

* Both Mushroom and Titanic are for supervised binary classification tasks
* Both have categorical-valued features
* Titanic rows have 3 features, Mushroom rows have 22

### CODE REVIEW

**Comment by ocramz** [comment]
Notes:

* Both Mushroom and Titanic are for supervised binary classification tasks 
* Both have categorical-valued features
* Titanic rows have 3 features, Mushroom rows have 21

**Comment by ocramz** [comment]
@glutamate the Travis tests are failing for a reason unrelated to this PR; is there something I should change or fix here?

**Comment by glutamate** [comment]
Apologies, I thought I merged this some time ago. Don't worry about the CI, it often breaks due to out of memory errors

**Comment by ocramz** [comment]
No worries, glad you liked it! I can't wait to try it out in a project, and I hope it'll be useful to others as well : )

**Comment by ocramz** [comment]
@glutamate could you upload a new Hackage release? Also, I'd be happy to help co-maintain this package if it's ok with you.

**Pull request merged**
